### ISSUE TITLE
"make update" pin wrong worker ip address for kubernetes setup

### ISSUE THREAD

**Issue by yimm0815** [OpenVisualCloud/Smart-City-Sample#318] opened 2020-01-07 18:33 UTC
when set up kubernetes with one master and one worker, the "make update" always pin wrong worker ip address thus generate error as below: 
Unable to negotiate with 10.233.182.20 port 22: no matching cipher found. Their offer: aes128-cbc,3des-cbc

but if comment the docker swarm part in update-image.sh makes kubectl grab the correct worker ip and works fine. thanks @ttao1 to analyze and assign to him to fix.

**Comment by ttao1** [comment] 2020-01-07 22:11
The IP of the master node is 10.233.183.30. However,  command "docker node inspect --format '{{.Status.Addr}}' nodeId" shows 10.233.182.20. The IP is not showing in the list of "ip a". 

After running " docker swarm leave --force" and "docker swarm init", the IP value printed by "docker node inspect --format '{{.Status.Addr}}' nodeId" is 10.233.183.30 which is correct. 

Since the issue cannot be reproduced, close it now.

**Closed by ttao1** 2020-01-07 22:11 UTC
